/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetogigalink;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class TelaViewTelefone extends javax.swing.JFrame {
    ConectaBanco conecta = new ConectaBanco();
    /**
     * Creates new form TelaViewTelefone
     */
    public TelaViewTelefone() {
        initComponents();
        setLocationRelativeTo(null);
        conecta.conectar();
        idCodTel.setVisible(false);
        idFornecedorTel.setEditable(false);
        lblId.setVisible(false);
        validaCampo.setVisible(false);
       
    }
    
    @Override
    public void setDefaultCloseOperation(int operation) {
        super.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void recebeId(String recebe){
        idFornecedorTel.setText(recebe);
        idCodTel.setText("");
        dddTel.setText("");
        telefoneTel.setText("");
        refTel.setText("");
        lblTelefones.setText("");
          try {

            Statement st = conecta.con.createStatement();
            ArrayList arr = new ArrayList();
         //   ArrayList ids = new ArrayList();
            ResultSet rs = st.executeQuery("Select * from telefone where idFornecedorTel = " + idFornecedorTel.getText());
            while(rs.next()){
                arr.add(("ID nº ")+(rs.getString("id")+ " - (" + rs.getString("dddTel") + ") " + rs.getString("telTel")));  
               // ids.add(rs.getString("id"));
                 idCodTel.setVisible(true);
                 lblId.setVisible(true);
            }
                    lblTelefones.setText("Telefones Cadastrados: " + (arr).toString().replace("[", "").replace("]", ""));
                    System.out.println((arr));

        } catch (SQLException ex) {
            Logger.getLogger(TelaViewFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGravarTel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        idFornecedorTel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idCodTel = new javax.swing.JTextField();
        telefoneTel = new javax.swing.JTextField();
        refTel = new javax.swing.JTextField();
        btnEditarTel = new javax.swing.JButton();
        dddTel = new javax.swing.JTextField();
        lblTelefones = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        validaCampo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGravarTel.setText("Gravar");
        btnGravarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarTelActionPerformed(evt);
            }
        });

        jLabel7.setText("ID do Fornecedor:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Telefone");

        lblId.setText("ID:");

        jLabel3.setText("Telefone");

        jLabel4.setText("Ref.:");

        btnEditarTel.setText("Consultar / Editar");
        btnEditarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTelActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblId)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addComponent(idCodTel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnEditarTel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnGravarTel)
                                .addGap(18, 18, 18)
                                .addComponent(btnAtualizar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(idFornecedorTel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dddTel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(telefoneTel))
                                            .addComponent(refTel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel1)))
                                .addGap(12, 12, 12)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(validaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(idCodTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(idFornecedorTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telefoneTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dddTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(refTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarTel)
                    .addComponent(btnGravarTel)
                    .addComponent(btnAtualizar)
                    .addComponent(jButton1)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addComponent(lblTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarTelActionPerformed

        try {

            Statement st = conecta.con.createStatement();
            st.executeUpdate("INSERT INTO telefone values('"+0+"', '"+idFornecedorTel.getText()+"', '"+dddTel.getText()+"', '"+telefoneTel.getText()+"', '"+refTel.getText()+"')");
            JOptionPane.showMessageDialog(null, "Telefone Gravado com Sucesso.");

        } catch (SQLException ex) {
            Logger.getLogger(TelaViewFornecedor.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnGravarTelActionPerformed

    private void btnEditarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTelActionPerformed
        validaCampo.setText("");
        try {

            Statement st = conecta.con.createStatement();
            ResultSet rs = st.executeQuery("Select * from telefone where id = " + idCodTel.getText());
            while(rs.next()){
                dddTel.setText(rs.getString("dddTel"));
                telefoneTel.setText(rs.getString("telTel"));
                refTel.setText(rs.getString("refTel"));
                validaCampo.setText(rs.getString("idFornecedorTel"));
                
            }
                
                if(validaCampo.getText().equals(idFornecedorTel.getText())){
                    dddTel.setEditable(true);
                    telefoneTel.setEditable(true);
                    refTel.setEditable(true);
                    btnGravarTel.setEnabled(false);
                }else{
                    dddTel.setEditable(false);
                    telefoneTel.setEditable(false);
                    refTel.setEditable(false);
                    JOptionPane.showMessageDialog(null, "Só é possível alterar os telefones listados abaixo");
                
            }
                   
        } catch (SQLException ex) {
            Logger.getLogger(TelaViewFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditarTelActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
         try {
             
            Statement st = conecta.con.createStatement();
            st.executeUpdate("UPDATE telefone set id = '"+idCodTel.getText()+"', idFornecedorTel = '"+idFornecedorTel.getText()+"', dddTel = '"+dddTel.getText()+"', telTel = '"+telefoneTel.getText()+"', refTel = '"+refTel.getText()+"' WHERE id = " + idCodTel.getText());
            JOptionPane.showMessageDialog(null, "Telefone Atualizado com Sucesso.");

        } catch (SQLException ex) {
            Logger.getLogger(TelaViewFornecedor.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                dddTel.setText("");
                telefoneTel.setText("");
                refTel.setText("");
                validaCampo.setText("");
                idCodTel.setText("");
                btnGravarTel.setEnabled(true);
                dddTel.setEditable(true);
                telefoneTel.setEditable(true);
                refTel.setEditable(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
          try {

            Statement st = conecta.con.createStatement();
            st.executeUpdate("DELETE FROM telefone WHERE id = " + idCodTel.getText());
            dddTel.setText("");
            telefoneTel.setText("");
            refTel.setText("");
            idCodTel.setText("");
            btnGravarTel.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Excluído com Sucesso");

        } catch (SQLException ex) {
            Logger.getLogger(TelaViewFornecedor.class.getName()).log(Level.SEVERE, null, ex);

        } 
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaViewTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaViewTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaViewTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaViewTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaViewTelefone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEditarTel;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravarTel;
    private javax.swing.JTextField dddTel;
    private javax.swing.JTextField idCodTel;
    private javax.swing.JTextField idFornecedorTel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTelefones;
    private javax.swing.JTextField refTel;
    private javax.swing.JTextField telefoneTel;
    private javax.swing.JTextField validaCampo;
    // End of variables declaration//GEN-END:variables
}
